name: Version bump
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Bump versions
        uses: remorses/bump-version@js
        with:
          prefix: dir1 # this will prefix the created tag
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump versions
          uses: remorses/bump-version@js
          with:
            prefix: dir2 # this will prefix the created tag
            github_token: ${{ secrets.GITHUB_TOKEN }}

