name: Version bump
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Automated Version Bump Server'
        uses: 'phips28/gh-action-bump-version@v8.0.12'
        with:
          PACKAGEJSON_DIR: 'dir1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Automated Version Bump Client'
        uses: 'phips28/gh-action-bump-version@v8.0.12'
        with:
          PACKAGEJSON_DIR: 'dir2'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
