name: Version bump
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Automated Version Bump Server'
        uses: 'phips28/gh-action-bump-version@v8.0.12'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
